### PR TITLE
Fold

### PR DESCRIPTION
**Pull request by rleonid**
Can we build fast folds for OCaml [Bigarrays](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Bigarray.html)? So far the answer as no, as the naive implementations seem to be ~5x slower than just native arrays.

### CODE REVIEW

**Comment by rleonid** [comment]
A little status report for posterity. After first trying to drop to native calls for the folds and not seeing spectacular results and then finding out about the special indexing primitives, I'm attempting a `ppx` solution. This should make it easier to write a fast fold 'function' (in this case a `ppx` macro).

**Comment by rleonid** [comment]
Features left to add:
- [ ] Correct error messages
- [ ] Labeled arguments
- [ ] Just `iter`

**Comment by rleonid** [comment]
Better error messages check

**Comment by rleonid** [comment]
Since the elements after an extension are parsed as structure elements by default [1], writing
```OCaml
let sum v = [%array1.fold_left.float64 ~f:(+.) ~init:0. v]
```
is a syntax error. One could write
```OCaml
let sum v = [%array1.fold_left.float64 v ~f:(+.) ~init:0.]
```
(the payload is parsed as a function v with 2 labeled arguments). I'm going to table adding this feature at the moment, since it would be surprising to a user to allow this.

1. There can also be signature, core_type and patterns but they all leave rather unsatisfying syntax.

**Comment by rleonid** [comment]
@ihodes I'm going to write a bit more documentation and do a final pass through the code to see if I can simplify it, but this is like an alpha-request for a review!

**Comment by ihodes** [comment]
It's going to be a while before I have internet again! But I look forward to this when I'm back :)

**Comment by rleonid** [comment]
No worries, enjoy your trip! I'll merge now then to avoid having to revisit this later.

**Pull request merged**
